version: '3.7'

services:
  initializer:
    build:
      context: ./initializer
      dockerfile: Dockerfile
    volumes:
      - env-data:/env
    command: /scripts/generate_env.sh
    healthcheck:
      test: ["CMD", "test", "-f", "/env/myenvfile"]
      interval: 5s
      timeout: 2s
      retries: 3

  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    volumes:
      - env-data:/env
    entrypoint: ["/scripts/wait-for-it.sh", "initializer:8000", "--"]
    command: ["/app/start_service.sh"]

  service2:
    build:
      context: ./service1
      dockerfile: Dockerfile
    volumes:
      - env-data:/env
    entrypoint: ["/scripts/wait-for-it.sh", "initializer:8000", "--"]
    command: ["/app/start_service.sh"]

volumes:
  env-data:

